### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by Daniel-Diaz** [dom96/SimpleIRC#21]
Any plans to upload a new version to Hackage? The version on Hackage is currently unbuildable with GHC-7.10. This issue was fixed by commit https://github.com/dom96/SimpleIRC/commit/577a9abb5f078c4c4b1c001cf763d7a3e5724bd1, but never reached Hackage.

Thanks!

**Comment by dom96** [comment]
Done

**Comment by Daniel-Diaz** [comment]
Thank you!
